name: nutriscan_ai
description: A Flutter app to scan, extract, and translate nutrition label text.
publish_to: 'none' # Remove this line if publishing

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_translation: ^0.10.1
  lottie: ^2.7.0
  glassmorphism: ^2.0.0
  image_picker: ^1.0.4
  animated_text_kit: ^4.2.2
  rive: ^0.12.3
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/scan.json
